# Generated by Django 3.2.5 on 2021-07-05 11:52

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('body', models.TextField(verbose_name='Body')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
                ('comment_parent', models.CharField(max_length=100, verbose_name='Comment Parent')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Comment Created On')),
                ('action_ip', models.CharField(max_length=20, verbose_name='Comment Posted IP')),
                ('comment_modified_at', models.DateTimeField(auto_now=True, verbose_name='Comment Modified On')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('excerpt', models.CharField(max_length=300, verbose_name='Post Excerpt')),
                ('thumbail', models.ImageField(upload_to=core.utils.upload_image_path, verbose_name='Post Thumbnail')),
                ('slug', models.SlugField(unique=True, verbose_name='Post Slug')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('views', models.IntegerField(verbose_name='Post Views')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('action_ip', models.CharField(max_length=20, verbose_name='Posted IP')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Post Modified At')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Post Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=50, verbose_name='Tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
    ]
