# Generated by Django 3.2.5 on 2021-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210711_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='action_ip',
            field=models.CharField(editable=False, max_length=20, verbose_name='Comment Posted IP'),
        ),
    ]
