# Generated by Django 3.2.5 on 2021-07-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_action_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=300, verbose_name='Post Excerpt'),
        ),
    ]
