# Generated by Django 3.2.5 on 2021-07-05 11:52

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text')),
                ('link', models.URLField(blank=True, verbose_name='Menu Link')),
            ],
            options={
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Page Title')),
                ('excerpt', models.CharField(max_length=300, verbose_name='Page Excerpt')),
                ('thumbail', models.ImageField(upload_to=core.utils.upload_image_path, verbose_name='Page Thumbnail')),
                ('slug', models.SlugField(unique=True, verbose_name='Page Slug')),
                ('content', models.TextField(verbose_name='Page Content')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Page Modified At')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Page Created At')),
            ],
        ),
    ]
