# Generated by Django 3.2.5 on 2021-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prefix_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='auth',
            field=models.SlugField(blank=True, help_text='Default: auth', verbose_name='Auth'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='author',
            field=models.SlugField(blank=True, help_text='Default: author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='category',
            field=models.SlugField(blank=True, help_text='Default: category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='homepage',
            field=models.SlugField(blank=True, help_text='Default: *', verbose_name='Homeage'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='page',
            field=models.SlugField(blank=True, help_text='Default: page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='post',
            field=models.SlugField(blank=True, help_text='Default: post', verbose_name='Single Post'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='posts',
            field=models.SlugField(blank=True, help_text='Default: posts', verbose_name='Posts List'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='tag',
            field=models.SlugField(blank=True, help_text='Default: tag', verbose_name='Tag'),
        ),
    ]
