# Generated by Django 3.2.5 on 2021-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210705_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefix',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='author',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='category',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='page',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='post',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='tag',
        ),
        migrations.AddField(
            model_name='prefix',
            name='destination',
            field=models.SlugField(default='a', verbose_name='Homeage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefix',
            name='link',
            field=models.SlugField(default='a', verbose_name='Posts List'),
            preserve_default=False,
        ),
    ]
