# Generated by Django 3.2.5 on 2021-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210705_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='destination',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='link',
            field=models.SlugField(verbose_name='Link Slug'),
        ),
    ]
