# Generated by Django 3.2.5 on 2021-07-05 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('core', '0007_auto_20210705_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prefix',
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Menu Link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.tag', verbose_name='Tag'),
        ),
    ]
