# Generated by Django 3.2.5 on 2021-07-06 05:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210706_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('target', models.CharField(max_length=10, verbose_name='Ad Target')),
                ('code', models.TextField(verbose_name='Ad Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Site Title')),
                ('excerpt', models.TextField(verbose_name='Site Excerpt')),
                ('logo', models.ImageField(upload_to=core.utils.upload_image_path, verbose_name='Site Logo')),
                ('favico', models.ImageField(upload_to=core.utils.upload_image_path, verbose_name='Site Favico')),
                ('footer_text', models.CharField(max_length=255, verbose_name='Footer Text')),
            ],
        ),
    ]
