# Generated by Django 3.2.5 on 2021-07-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ad_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(choices=[('test', 'test')], max_length=150, unique=True, verbose_name='Site Title'),
        ),
    ]
