# Generated by Django 3.2.5 on 2021-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Link'),
        ),
    ]
