# Generated by Django 3.2.5 on 2021-07-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_menu_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='target',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ad Target'),
        ),
    ]
