# Generated by Django 3.2.5 on 2021-07-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_action_ip'),
        ('core', '0015_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Link')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Category')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.page', verbose_name='Page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name_plural': 'Footer Menu Items',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Link')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Category')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.page', verbose_name='Page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name_plural': 'Main Menu Items',
            },
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Menu Link')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.category', verbose_name='Category')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.page', verbose_name='Page')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name_plural': 'Top Menu Items',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
