# Generated by Django 3.2.5 on 2021-07-11 17:56

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210711_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='thumbail',
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=core.utils.upload_image_path, verbose_name='Page Thumbnail'),
        ),
        migrations.AlterField(
            model_name='page',
            name='excerpt',
            field=models.TextField(max_length=300, verbose_name='Page Excerpt'),
        ),
    ]
