# Generated by Django 3.2.5 on 2021-07-12 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_excerpt'),
        ('core', '0018_auto_20210711_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('section_one', 'Section One'), ('section_two', 'Section Two'), ('section_three', 'Section Three')], max_length=50, unique=True, verbose_name='Section')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='Category')),
            ],
        ),
    ]
