# Generated by Django 3.2.5 on 2021-07-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Homepage'},
        ),
        migrations.AlterField(
            model_name='footermenu',
            name='text',
            field=models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, null=True, verbose_name='Menu Text'),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text',
            field=models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, null=True, verbose_name='Menu Text'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='text',
            field=models.CharField(blank=True, help_text='Displayed in case of link menu', max_length=100, null=True, verbose_name='Menu Text'),
        ),
    ]
