# Generated by Django 3.2.5 on 2021-07-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210717_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footermenu',
            name='text',
            field=models.CharField(blank=True, default='d', help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='text',
            field=models.CharField(blank=True, default='d', help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='text',
            field=models.CharField(blank=True, default='d', help_text='Displayed in case of link menu', max_length=100, verbose_name='Menu Text'),
            preserve_default=False,
        ),
    ]
