# Generated by Django 3.2.5 on 2021-07-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210718_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Format: +977 98XXXXXXXX', max_length=15, null=True, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Contact Date')),
            ],
        ),
    ]
